##############################
### WINDOWS AND WORKSPACES ###
##############################

# --- Global rules ---
windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-dummy
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# --- Pavucontrol ---
windowrule {
    name = pavucontrol-floating
    match:class = ^org.pulseaudio.pavucontrol$
    float = true
    center = true
    size = 800 600
}

# --- Calculadora ---
windowrule {
    name = calculator-floating
    match:class = ^org.gnome.Calculator$
    float = true
    center = true
    size = 700 500
}

# --- Blueman ---
windowrule {
    name = blueman-floating
    match:class = ^blueman-manager$
    float = true
    center = true
    size = 700 500
}

# --- Portal GTK ---
windowrule {
    name = portal-gtk-floating
    match:class = ^xdg-desktop-portal-gtk$
    float = true
    center = true
}

# --- Gimp floats ---
windowrule {
    name = gimp-dialog-float
    match:class = ^file-\w*$
    float = true
    center = true
}

# --- PiP ---
windowrule {
    name = pip-floating
    match:title = ^Imagen en imagen$
    float = true
    center = true
}
